### ISSUE TITLE
Licence ?

### ISSUE THREAD

**Issue by trebmuh** [grame-cncm/smartfaust#1]
I'm wondering what is the license of smartfaust.

**Comment by sletz** [comment]
BSD

**Comment by trebmuh** [comment]
OK, thanks Stéphane

**Comment by trebmuh** [comment]
OK, thanks Stéphane.
It'd be great to add that to the repo if you have time to do so.

**Comment by sletz** [comment]
It is in the file themselves.

**Comment by trebmuh** [comment]
Seems to be a mix between different licenses if I'm to believe [a search throught the repo](https://github.com/grame-cncm/smartfaust/search?q=declare+license).

Au passage, il y a [quelques "franciseries"](https://github.com/grame-cncm/smartfaust/search?q=declare+licence). :)
